# Generated by Django 3.1.2 on 2021-02-03 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('loaction', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sale_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('machines', models.ManyToManyField(to='mainApp.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField()),
                ('amount', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='mainApp.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='mainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField()),
                ('amount', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restocks', to='mainApp.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restocks', to='mainApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='products',
            field=models.ManyToManyField(to='mainApp.Product'),
        ),
    ]
