# Generated by Django 3.1.2 on 2021-02-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='mainApp.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='machines',
            field=models.ManyToManyField(blank=True, null=True, to='mainApp.Machine'),
        ),
    ]
