# Generated by Django 3.1.2 on 2021-02-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210203_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='value',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='transaction',
            name='revenue',
            field=models.IntegerField(default=None),
        ),
    ]
