# Generated by Django 3.1.2 on 2021-02-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_machine_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='machines',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='mainApp.Machine'),
        ),
    ]
